### ISSUE TITLE
v0.10.3 fails to build due to error in bazel-integration-testing//tools:common.bzl dependency

### ISSUE THREAD

**Issue by sudoforge** [bazelbuild/bazel-watcher#297]
Per #296, I'm creating this issue to report that the tag `v0.10.3` fails to build.

```
➜ bazel version
Build label: 0.29.1- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Oct 9 11:51:48 2019 (1570621908)
Build timestamp: 1570621908
Build timestamp as int: 1570621908

➜ git checkout v0.10.3
...
HEAD is now at 1c7e9c2 Generating CHANGELOG.md for release v0.10.3

➜ bazel build ...
Starting local Bazel server and connecting to it...
ERROR: /home/sudoforge/code/src/github.com/bazelbuild/bazel-watcher/e2e/output_runner/BUILD:4:1: Traceback (most recent call last):
        File "/home/sudoforge/code/src/github.com/bazelbuild/bazel-watcher/e2e/output_runner/BUILD", line 4
                bazel_go_integration_test(name = "go_default_test", srcs = [..."], <4 more arguments>)
        File "/home/sudoforge/code/src/github.com/bazelbuild/bazel-watcher/e2e/output_runner/BUILD", line 11, in bazel_go_integration_test
                GET_LATEST_BAZEL_VERSIONS()
        File "/home/sudoforge/.cache/bazel/_bazel_sudoforge/3b1e4f7feeec122a0d31aa649ea63d08/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 65, in GET_LATEST_BAZEL_VERSIONS
                ".".join(v)
sequence element must be a string (got 'int'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.
ERROR: /home/sudoforge/code/src/github.com/bazelbuild/bazel-watcher/e2e/simple/BUILD:6:1: Traceback (most recent call last):
        File "/home/sudoforge/code/src/github.com/bazelbuild/bazel-watcher/e2e/simple/BUILD", line 6
                bazel_go_integration_test(name = "go_default_test", srcs = [..."], <4 more arguments>)
        File "/home/sudoforge/code/src/github.com/bazelbuild/bazel-watcher/e2e/simple/BUILD", line 13, in bazel_go_integration_test
                GET_LATEST_BAZEL_VERSIONS()
        File "/home/sudoforge/.cache/bazel/_bazel_sudoforge/3b1e4f7feeec122a0d31aa649ea63d08/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 65, in GET_LATEST_BAZEL_VERSIONS
                ".".join(v)
sequence element must be a string (got 'int'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.
ERROR: /home/sudoforge/code/src/github.com/bazelbuild/bazel-watcher/e2e/profiler/BUILD:6:1: Traceback (most recent call last):
        File "/home/sudoforge/code/src/github.com/bazelbuild/bazel-watcher/e2e/profiler/BUILD", line 6
                bazel_go_integration_test(name = "go_default_test", srcs = [..."], <4 more arguments>)
        File "/home/sudoforge/code/src/github.com/bazelbuild/bazel-watcher/e2e/profiler/BUILD", line 13, in bazel_go_integration_test
                GET_LATEST_BAZEL_VERSIONS()
        File "/home/sudoforge/.cache/bazel/_bazel_sudoforge/3b1e4f7feeec122a0d31aa649ea63d08/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 65, in GET_LATEST_BAZEL_VERSIONS
                ".".join(v)
sequence element must be a string (got 'int'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.
ERROR: /home/sudoforge/code/src/github.com/bazelbuild/bazel-watcher/e2e/live_reload/BUILD:6:1: Traceback (most recent call last):
        File "/home/sudoforge/code/src/github.com/bazelbuild/bazel-watcher/e2e/live_reload/BUILD", line 6
                bazel_go_integration_test(name = "go_default_test", srcs = [..."], <4 more arguments>)
        File "/home/sudoforge/code/src/github.com/bazelbuild/bazel-watcher/e2e/live_reload/BUILD", line 13, in bazel_go_integration_test
                GET_LATEST_BAZEL_VERSIONS()
        File "/home/sudoforge/.cache/bazel/_bazel_sudoforge/3b1e4f7feeec122a0d31aa649ea63d08/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 65, in GET_LATEST_BAZEL_VERSIONS
                ".".join(v)
sequence element must be a string (got 'int'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.
ERROR: package contains errors: e2e/profiler
ERROR: package contains errors: e2e/simple
ERROR: package contains errors: e2e/live_reload
ERROR: package contains errors: e2e/output_runner
ERROR: error loading package 'e2e/profiler': Package 'e2e/profiler' contains errors
INFO: Elapsed time: 3.621s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded)
```

Looks like the [`GET_LATEST_BAZEL_VERSIONS`](https://github.com/bazelbuild/bazel-integration-testing/blob/master/tools/common.bzl#L19) symbol from `@com_github_bazelbuild_bazel_integration_testing//tools:common.bzl` is erroneous.

The `@com_github_bazelbuild_bazel_integration_testing` repository is currently pinned at commit `83c0657f503f382f12bcd2ce3736a72196ef5e5e`. In the upstream repository, a fix for the `incompatible_string_join_requires_strings` error is available in commit [`5cba515a8174b9f96c47c789c3fecbcb1e5e9934`](https://github.com/bazelbuild/bazel-integration-testing/commit/5cba515a8174b9f96c47c789c3fecbcb1e5e9934).

I tested updating the dependency version, but ran into other dependency issues (first `@com_github_bazelbuild_rules_go` then `@com_github_golang_protobuf`). I don't have the time to chase the issue down tonight but am leaving this here as a record.

**Comment by sudoforge** [comment]
It should be noted that `HEAD` builds fine (as of commit `5603789ae9b1bb4c56b3dbd35b7dde7d3e3e2e72`).

**Comment by achew22** [comment]
I'm happy to force push a tag if it means fixing things for everyone. I've just replaced the `v0.10.3` tag with the current HEAD and this should fix the issue for you. Sorry for any trouble this caused.
