### ISSUE TITLE
segfault in iBazel in NotifyOfChanges

### ISSUE THREAD

**Issue by achew22** [bazelbuild/bazel-watcher#411]
**Describe the bug**
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5c4cf5]                                                                                                                            [42/1969]

goroutine 1 [running]:
github.com/bazelbuild/bazel-watcher/ibazel/command.(*defaultCommand).Terminate(0xc00010c070)
        ibazel/command/default_command.go:55 +0x45
github.com/bazelbuild/bazel-watcher/ibazel/command.(*defaultCommand).NotifyOfChanges(0xc00010c070, 0x5)
        ibazel/command/default_command.go:84 +0x2b
main.(*IBazel).run(0xc00010e000, 0xc0000a6df0, 0x1, 0x1, 0x2, 0x3, 0xc00007c020)
        ibazel/ibazel.go:416 +0x1b6
main.(*IBazel).iteration(0xc00010e000, 0x878840, 0x3, 0xc000073e10, 0xc0000a6df0, 0x1, 0x1, 0x7fff8de1b3f2, 0x10)
        ibazel/ibazel.go:326 +0x228
main.(*IBazel).loop(0xc00010e000, 0x878840, 0x3, 0xc000073e10, 0xc0000a6df0, 0x1, 0x1, 0xc0000a6dd0, 0x0)
        ibazel/ibazel.go:270 +0xfb
main.(*IBazel).Run(0xc00010e000, 0x7fff8de1b3f2, 0x10, 0xc0000a6de0, 0x1, 0x1, 0x0, 0x0)
        ibazel/ibazel.go:252 +0xe3
main.handle(0xc00010e000, 0x7fff8de1b3ee, 0x3, 0xc0000d0020, 0x3, 0x3)
        ibazel/main.go:191 +0x12d
main.main()
        ibazel/main.go:176 +0x2f9
```

**Reproduction instructions**
Happens intermittently and infrequently. Hadn't seen it prior to today.
 
**Expected behavior**
No crash

**Version (please complete the following information):**
 - OS: Linux
 - ibazel Version [e.g. 0.13.1] (run `ibazel 2>&1 | head -n 1` to get this)
 - Bazel version [e.g. 3.4.1] (run `bazel version` to get this. Please include all the lines)
 
**Additional context**
Nope

**Comment by achew22** [comment]
May be triggerable by killing a subprocess with ctrl-c and then saving the file to trigger a run?
