### ISSUE TITLE
Apple silicon support?

### ISSUE THREAD

**Issue by Jakob-em** [bazelbuild/bazel-watcher#482]
**Describe the bug**
When running the ibazel version downloaded by npm I get the following error on an M1 Mac:

```
ibazel run //src:devserver
FATAL: Your platform/architecture combination darwin - arm64 is not yet supported.
    Follow install instructions at https://github.com/bazelbuild/bazel-watcher/blob/master/README.md to compile for your system.
node:internal/validators:119
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received an instance of Promise
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at normalizeSpawnArguments (node:child_process:503:3)
    at spawn (node:child_process:691:13)
    at main (/Users/jakob/.nvm/versions/node/v16.11.1/lib/node_modules/@bazel/ibazel/index.js:82:18)
    at Object.<anonymous> (/Users/jakob/.nvm/versions/node/v16.11.1/lib/node_modules/@bazel/ibazel/index.js:96:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

1. `git clone git@github.com:bazelbuild/rules_nodejs.git`
2. `cd examples/angular`
2. `ibazel run //src:devserver`

**Version (please complete the following information):**
 - OS: macOS Big Sur 11.6
 - ibazel version: -
 - Bazel version: 4.2.1-homebrew

**Comment by mistic** [comment]
I believe this is another urgent thing to work on @achew22 as both bazelisk and bazel already supports `darwin_arm64` natively.

**Comment by Splaktar** [comment]
This issue is still a problem.
