### ISSUE TITLE
installs error

### ISSUE THREAD

**Issue by istiti** [bazelbuild/bazel-watcher#90]
I definitly don't understand what's wrong here: 

```
PS C:\Users\ee\Desktop\r\bazel-watcher-master> bazel build //ibazel
WARNING: C:/users/ee/appdata/local/temp/_bazel_ee/vzadcu2y/external/com_github_bazelbuild_bazel_integration_testing/WORKSPACE:1: Workspace name in C:/users/ee/appdata/local/temp/_bazel_ee/vzadcu2y/external/com_github_bazelbuild_bazel_integration_testing/WORKSPACE (@build_bazel_integration_testing) does not match the name given in the repository's definition (@com_github_bazelbuild_bazel_integration_testing); this will cause a build error in future versions.
DEBUG: C:/users/ee/appdata/local/temp/_bazel_ee/vzadcu2y/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
.
DEBUG: C:/users/ee/appdata/local/temp/_bazel_ee/vzadcu2y/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS
.
DEBUG: C:/users/ee/appdata/local/temp/_bazel_ee/vzadcu2y/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
.
DEBUG: C:/users/ee/appdata/local/temp/_bazel_ee/vzadcu2y/external/io_bazel_rules_go/go/private/toolchain.bzl:97:5: java.io.IOException: CreateProcess(): Le fichier spÚcifiÚ est introuvable.
.
ERROR: C:/users/ee/appdata/local/temp/_bazel_ee/vzadcu2y/external/io_bazel_rules_go/go/toolchain/BUILD.bazel:8:1: every rule of type _go_toolchain implicitly depends upon the target '@go_sdk//:packages.txt', but this target could not be found because of: no such package '@go_sdk//': Traceback (most recent call last):
        File "C:/users/ee/appdata/local/temp/_bazel_ee/vzadcu2y/external/io_bazel_rules_go/go/private/toolchain.bzl", line 45
                _prepare(ctx)
        File "C:/users/ee/appdata/local/temp/_bazel_ee/vzadcu2y/external/io_bazel_rules_go/go/private/toolchain.bzl", line 98, in _prepare
                fail("failed to list standard package...")
failed to list standard packages.
ERROR: Analysis of target '//ibazel:ibazel' failed; build aborted.
INFO: Elapsed time: 97,087s
```

It seems bazel's working cause I succeed to install `bazel build //examples/cpp:hello-world` from bazel-master/examples

**Comment by achew22** [comment]
Right now ibazel do not support Windows. I don't have a box to test on, but the complexities of it are 

As I see it there are 2 things that need to happen:

1.  Until there are windows binaries made available, we should delete windows from our [list of supported OSes](https://github.com/bazelbuild/bazel-watcher/blob/master/npm/index.js#L32) PRs welcome to do that. I'll do a release to NPM when that happens.
1.  Identify the all the windows specific APIs that need to be reimplemented. I used fsnotify which should be OS agnostic, but I think the process group code in the commands section needs to be updated to use whatever a windows equivalent command would be.

**Comment by achew22** [comment]
Progress here is being tracked in #105. Let's consolidate
